# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: $GITHUB_WORKSPACE/ci-settings.xml # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/ci-settings.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/ci-settings.xml
      env:
        SETTINGS_XML_USERNAME: ${{ secrets.SETTINGS_XML_USERNAME }}
        SETTINGS_XML_PASSWORD: ${{ secrets.SETTINGS_XML_PASSWORD }}
